name: auto-merge

on:
  pull_request_review:
  pull_request_target:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        # Yeah, lets not leave it this way
        # if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.ARBOR_AUTO_MERGE }}
          merge-method: rebase
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
