name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: \
          echo "test"
          echo "${{ github.actor }}"
          echo "test2"

      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
