name: auto-merge

on:
  pull_request_review:

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: reitermarkus/automerge@v1
        if: github.event.review.state == 'approved' || !github.event.review
        with:
          token: ${{ secrets.ARBOR_BOT_PAT }}
          merge-method: rebase
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
