name: PR Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - run: \
          echo '${{ github_event_path }}'
          echo 'cat ${{ github_event_path }}'
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
