name: 'Request Review'

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Trigger CI Bot'
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        uses: kunihiko-t/review-request-action@v0.1.3
        with:
          repo-token: ${{ secrets.TOKEN }}
          reviewers: 'arbor-ci'
